#!/usr/bin/env python

import os, re, subprocess, sys

def format_bandwidth(bits):
  if bits >= 1000000:
    return "%.2f Mbit/s" % (bits / 1000000)
  elif bits >= 1000:
    return "%.2f kbit/s" % (bits / 1000)
  else:
    return "%.2f bit/s" % bits

if __name__ == "__main__":
  if len(sys.argv) != 3:
    script_name = os.path.basename(sys.argv[0])
    print "Usage: %s WARN CRIT" % script_name
    sys.exit(0)

  (warn, crit) = sys.argv[1:3]
  warn = int(sys.argv[1])
  crit = int(sys.argv[2])

  process_output = subprocess.check_output(["bwm-ng", "-I", "eth0", "-t", "5000", "-c", "1", "-o", "csv"])
  data = process_output.splitlines()[0].split(";")
  tx = float(data[2]) * 8
  rx = float(data[3]) * 8
  status = "rx %s tx %s" % (format_bandwidth(rx), format_bandwidth(tx))

  perfdata = "rx=%i;%i;%i tx=%i;%i;%i" % (rx, warn, crit, tx, warn, crit)

  output = "%s|%s" % (status, perfdata)

  if rx >= crit or tx >= crit:
    print "CRITICAL - " + output
    sys.exit(2)

  if rx >= warn or tx >= warn:
    print "WARNING - " + output
    sys.exit(1)

  print "OK - " + output
