classes:
  statsclient:
  web::server:
    vhost: acceptableads.org
    certificate: acceptableads.org_sslcert.pem
    private_key: acceptableads.org_sslcert.key
    is_default: true
    repository: web.acceptableads.org

