classes:
  web::server:
    vhost: acceptableads.com
    aliases:
      - www.acceptableads.com
      - acceptableads.org
      - www.acceptableads.org
    custom_config: |
      rewrite ^(/..)?/[Pp]latform$ $1/tool-certification permanent;
    is_default: true
    multiplexer_locations:
      - /committee/apply/submit
    repository: web.acceptableads.com
  sitescripts::formmail:

committee_application_template: &committee_application_template |
  To: committee@acceptableads.org,committee@eyeo.com
  From: donotreply@adblockplus.org
  Reply-To: {{(fields.name,fields.email)|emailaddr|mime}}
  Subject: Submission for Acceptable Ads committee by {{fields.name|mime}} from {{fields.company|mime}}
  Content-Transfer-Encoding: 8bit
  Content-Type: text/plain; charset="UTF-8"

  {{fields.name}} would like to apply for the Acceptable Ads committee:

  Name: {{fields.name}}
  Title: {{fields.title}}
  Company: {{fields.company}}
  Email: {{fields.email}}
  Phone: {{fields.phone}}
  Group: {{fields.group}}

  Motivation:
  {{fields.motivation}}

sitescripts::formmail::templates:
  committee.mail:
    content: *committee_application_template

sitescripts::configfragments:
  committee_form:
    content: |
      [DEFAULT]
      mailer=/usr/sbin/sendmail
      mailerDebug=no
      [multiplexer]
      sitescripts.formmail.web.formmail =
      [formmail]
      committee.url = /committee/apply/submit
      committee.csv_log = /var/log/committee_email.csv_log
      committee.template = /var/sitescripts/formmail/committee.mail
      committee.fields.name = mandatory
      committee.fields.title = mandatory
      committee.fields.title.mandatory = No job title entered
      committee.fields.company = mandatory
      committee.fields.company.mandatory = No company name entered
      committee.fields.email = mandatory, email
      committee.fields.email.email = Invalid email address
      committee.fields.phone =
      committee.fields.group = mandatory
      committee.fields.group.mandatory = No group selected
      committee.fields.motivation =

logrotate::config:
  committee_email_data:
    content: |
      /var/log/committee_email {
        weekly
        rotate 30
        compress
        missingok
        nodateext
      }
    ensure: 'present'
