classes:
  web::server:
    vhost: acceptableads.com
    aliases:
      - www.acceptableads.com
      - acceptableads.org
      - www.acceptableads.org
    custom_config: |
      rewrite ^(/..)?/[Pp]latform$ $1/tool-certification permanent;
    is_default: true
    multiplexer_locations:
      - /committee/apply/submit
    repository: web.acceptableads.com

sitescripts::configfragments:
  committee_form:
    content: |
      [DEFAULT]
      mailer=/usr/sbin/sendmail
      mailerDebug=no
      [multiplexer]
      sitescripts.formmail.web.formmail2 =
      [formmail2]
      committee.url = /committee/apply/submit
      committee.template = formmail/template/committee.mail
      committee.fields.name = mandatory
      committee.fields.title = mandatory
      committee.fields.title.mandatory = No job title entered
      committee.fields.company = mandatory
      committee.fields.company.mandatory = No company name entered
      committee.fields.email = mandatory, email
      committee.fields.email.email = Invalid email address
      committee.fields.phone =
      committee.fields.group = mandatory
      committee.fields.group.mandatory = No group selected
      committee.fields.motivation =

