classes:
  adblockplus::web::mimeo:
    format: $remote_addr - - [$time_local] "$request" $status $bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for" - "$http_accept_language" "$http_host" "$http_x_client_id" $http_content_length "$http_content_type" $request_body
    response: All good, carry on!
    port: 8000
  web::server:
    vhost: adblockbrowser.org
    aliases:
      - www.adblockbrowser.org
    is_default: true
    custom_config: |
      location /submit-feedback {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header User-Agent $http_user_agent;
        proxy_set_header Referer $http_referer;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Accept-Language $http_accept_language;
        proxy_set_header Host $http_host;
        proxy_set_header X-Client-Id $http_x_client_id;
      }
      location /badadssuck {
        rewrite ^(.*) https://eyeo.to/$1 redirect;
      }
    repository: web.adblockbrowser.org
    multiplexer_locations:
      - /sendInstallationLink

logrotate::config:
  adblockbrowser_feedback_data:
    content: |
      /var/log/nginx/adblockbrowser_feedback {
        daily
        rotate 30
        compress
        missingok
        nodateext
        sharedscripts
        postrotate
          [ ! -f /var/run/nginx.pid ] || kill -USR1 `cat /var/run/nginx.pid`
        endscript
      }
    ensure: 'present'

sitescripts::configfragments:
  installation_link:
    content: |
      [DEFAULT]
      mailer=/usr/sbin/sendmail
      [multiplexer]
      sitescripts.send_installation_link.web.send_installation_link =
      [send_installation_link]
      email_template=send_installation_link/template/adblockbrowser_installation_link.tmpl

