classes:
  web::server:
    vhost: adblockbrowser.org
    aliases:
      - www.adblockbrowser.org
    is_default: true
    custom_config: |
      location = /submit-feedback/ {
        access_log /var/log/nginx/adblockbrowser_feedback data;
        echo_read_request_body;
      }
    repository: web.adblockbrowser.org
    multiplexer_locations:
      - /sendInstallationLink

logrotate::config:
  adblockbrowser_feedback_data:
    content: |
      /var/log/nginx/adblockbrowser_feedback {
        daily
        rotate 30
        compress
        missingok
        nodateext
        sharedscripts
        postrotate
          [ ! -f /var/run/nginx.pid ] || kill -USR1 `cat /var/run/nginx.pid`
        endscript
      }
    ensure: 'present'

sitescripts::configfragments:
  installation_link:
    content: |
      [DEFAULT]
      mailer=/usr/sbin/sendmail
      [multiplexer]
      sitescripts.send_installation_link.web.send_installation_link =
      [send_installation_link]
      email_template=send_installation_link/template/adblockbrowser_installation_link.tmpl

