classes:
  adblockplus::web::mimeo:
    format: $remote_addr - - [$time_local] "$request" $status $bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for" - "$http_accept_language" "$http_host" "$http_x_client_id" $http_content_length "$http_content_type" $request_body
    response: All good, carry on!
    port: 8000
  web::server:
    vhost: adblockbrowser.org
    aliases:
      - www.adblockbrowser.org
    is_default: true
    custom_config: |
      rewrite ^/android-support/faq/?$ https://adblockplus.org/forum/viewforum.php?f=15 permanent;
      rewrite ^/android-support/?$ https://adblockplus.org/forum/viewforum.php?f=15 permanent;
      rewrite ^/android-support/privacy-options/?$ https://adblockplus.org/forum/viewforum.php?f=15 permanent;
      rewrite ^/android-support/acceptable-ads-config/?$ https://adblockplus.org/forum/viewforum.php?f=15 permanent;
      rewrite ^/ios-support/?$ https://adblockplus.org/forum/viewforum.php?f=26 permanent;
      rewrite ^/es-ES/?$ https://adblockbrowser.org/es/ permanent;
      rewrite ^/android-support/install/?$ https://adblockplus.org/forum/viewforum.php?f=15 permanent;
      rewrite ^/ios-support/additional-filter-lists/?$ https://adblockplus.org/forum/viewforum.php?f=26 permanent;
      rewrite ^/android-support/customizing-abb/?$ https://adblockplus.org/forum/viewforum.php?f=15 permanent;
      rewrite ^/android-support/adding-filter-list/?$ https://adblockplus.org/forum/viewforum.php?f=15 permanent;
      rewrite ^/android-support/changing-language https://adblockplus.org/forum/viewforum.php?f=15 permanent;
      rewrite ^/ios-support/changing-search-engine/?$ https://adblockplus.org/forum/viewforum.php?f=26 permanent;
      rewrite ^/ios-support/view-whitelisted-websites/?$ https://adblockplus.org/forum/viewforum.php?f=26 permanent;
      rewrite ^/ios-support/adding-filter-list/?$ https://adblockplus.org/forum/viewforum.php?f=26 permanent;
      rewrite ^/ios-support/disable-search-suggestions/?$ https://adblockplus.org/forum/viewforum.php?f=26 permanent;
      rewrite ^/ios-support/acceptable-ads-config/?$ https://adblockplus.org/forum/viewforum.php?f=26 permanent;
      rewrite ^/zh-CN/?$ https://adblockbrowser.org/zh_CN/ permanent;
      rewrite ^/android-support/removing-filter-list/?$ https://adblockplus.org/forum/viewforum.php?f=15 permanent;
      rewrite ^/ios-support/install/?$ https://adblockplus.org/forum/viewforum.php?f=26 permanent;
      rewrite ^/android-support/display-options/?^ https://adblockplus.org/forum/viewforum.php?f=15 permanent;
      rewrite ^/blog/?$ https://adblockplus.org/blog/ permanent;
      rewrite ^/zh-CN/android-support/customizing-abb/?$ https://adblockplus.org/forum/viewforum.php?f=15 permanent;
      rewrite ^/pt-BR/android-support/acceptable-ads-config/?$ https://adblockplus.org/forum/viewforum.php?f=15 permanent;
      rewrite ^/es-ES/android-support/changing-language/?$ https://adblockplus.org/forum/viewforum.php?f=15 permanent;
      rewrite ^/es-ES/android-support/removing-filter-list/?$ https://adblockplus.org/forum/viewforum.php?f=15 permanent;
      rewrite ^/index.html https://adblockbrowser.org/ permanent;
      rewrite ^/android/? https://adblockplus.org/forum/viewforum.php?f=15 permanent;
      rewrite ^/pt-PT/android-support/?$ https://adblockplus.org/forum/viewforum.php?f=15 permanent;
      rewrite ^/ios-support/removing-filter-list/?$ https://adblockplus.org/forum/viewforum.php?f=26 permanent;
      rewrite ^/zh-CN/android-support/adding-filter-list/?$ https://adblockplus.org/forum/viewforum.php?f=15 permanent;
      rewrite ^/zh-TW/ios-support/install/?$ https://adblockplus.org/forum/viewforum.php?f=26 permanent;
      location ~ /forum/view(forum|topic) {
       rewrite ^/forum/view(forum|topic) https://adblockplus.org/forum/view$1.php permanent;
      }
      location /submit-feedback {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header User-Agent $http_user_agent;
        proxy_set_header Referer $http_referer;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Accept-Language $http_accept_language;
        proxy_set_header Host $http_host;
        proxy_set_header X-Client-Id $http_x_client_id;
      }
      location /badadssuck {
        rewrite ^(.*) https://eyeo.to/$1 redirect;
      }
    repository: web.adblockbrowser.org
    multiplexer_locations:
      - /sendInstallationLink

logrotate::config:
  adblockbrowser_feedback_data:
    content: |
      /var/log/nginx/adblockbrowser_feedback {
        daily
        rotate 30
        compress
        missingok
        nodateext
        sharedscripts
        postrotate
          [ ! -f /var/run/nginx.pid ] || kill -USR1 `cat /var/run/nginx.pid`
        endscript
      }
    ensure: 'present'

sitescripts::configfragments:
  installation_link:
    content: |
      [DEFAULT]
      mailer=/usr/sbin/sendmail
      [multiplexer]
      sitescripts.send_installation_link.web.send_installation_link =
      [send_installation_link]
      email_template=send_installation_link/template/adblockbrowser_installation_link.tmpl

