classes:
  adblockplus:
  adblockplus::mercurial:
  adblockplus::puppet::agent:
  adblockplus::sudo:
  nagios::client:
    server_address: monitoring.adblockplus.org
  fail2ban:

adblockplus::mercurial::extensions:
  hggit:
    package:
      ensure: 0.8.9
      name: hg-git
      provider: pip
      install_options:
        - https://pypi.python.org/pypi/hg-git

adblockplus::log::uplink:
  log@log1.adblockplus.org

adblockplus::packages:
  - "debian-goodies"
  - "python-dev"
  - "python-pip"
  - "vim"

adblockplus::users:
  test:
    authorized_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDLrPR2CZLSs6tKSEUBeaahzcKhWwQAN9Hwcrn5HpS0FTz3VFbyJXNP5KZYci3zF6/CHNSM1iOkV6t/6U8g16+PWOo5pMNg7jWqoZD6ukT+cX6ZuNm8CtIx7EzwFxGB8INrKAonmpG9FRWHMppi4nJG5SrQv2rgoUDt+Dbu2oPMh/EGUS2wQ7VUwA1/qAeRsAdptrGB6wr/+1fGTdrZy11AG+sLnrO+VXIShOFCuv9czbj9nw5Bi6jwnWrzvfQx1BfwVwYtdfGSprB6p+8aL7u3SCF+aJAGGRoYjqec4+EM5xRJ3grmoFtkngEiJIaLWRPkgD8uggY2spmff1Ypl24v test@example.com"
    groups:
      - adm
      - staff
      - sudo
      - users
    password_hash: "$6$k.fe9F4U$OIav.SJZuujVfXk4HTKS.i94ZuQtoJNCH6KH1ePar57yc3y51G0PbGPXT6zO5v.q3h5TM87MDx0QEX4TTENq.0"

cron::environment:
  - MAILTO=root,vagrant

