---
servers:
  filter1:
    ip: [10.8.0.120]
    role: filterserver
    ssh_public_key: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBAUhHiFdqQBATyyOE9XPR7v2+bghp3r1QY0O62d/klV7yhAOBKQuI6MtTu43cYQE60M10OzVfeeMfmc0dPP97UM=
    groups: [filter-servers]
  server4:
    ip: [10.8.0.99]
    role: monitoringserver
    dns: server_4.adblockplus.org
    groups: [http-servers]
  codereview1:
    ip: [10.8.0.132]
    role: codereviewserver
    groups: [http-servers]
  download1:
    ip: [10.8.0.126]
    ssh_public_key: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBE9gWnTMFJkJ6DqrmnmQvOHyK/yaWvz6SKPetMX/A6avRLm4AzinvD+F7z4mIqRbJxhJgRljOxZWVgWCOQEWYaY=
    dns: downloads.adblockplus.org
    groups: [http-servers]
  filtermaster1:
    ip: [10.8.0.127]
  server10:
    ip: [10.8.0.105]
    role: intraforumserver
    ssh_public_key: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPoK6neBTjJIzWn6xhJozABPJoZ7809RmSOgBHKgbSMztjJD839Vbi263An4YgAhYijclPDX78zxjO0XgvW1aMc=
    dns: server_10.adblockplus.org
    groups: [http-servers]
  issues1:
    ip: [10.8.0.131]
    groups: [http-servers]
  stats1:
    ip: [10.8.0.130]
    groups: [http-servers]
  update1:
    ip: [10.8.0.128]
    ssh_public_key: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNQ4C/hghKhYSQHiz3cquPVbbMP5tycwHChe5gbY03jVR9dynO6Ldb5MWL02r83zFisPqM6lvtnjuGA65dzVJYE=
    groups: [http-servers]
  web1:
    ip: [10.8.0.129]
    ssh_public_key: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMu0mGhPAhIbAv7H0iN74h6fC9H2576AxI9cXFj3FAQxHl2ItLIibrViThm0luOJiRIaLc1GxavBKK0dR4bzFR8=
    groups: [http-servers]
  web2:
    ip: [10.8.0.145]
    ssh_public_key: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDhC6a20iZh6VurNrRC3ZzdilTp6yelnzJ8/49ujHvkAC38Rj6870re3Yvkg+8AfxdyVNP8owqC6x7KQD0zJ6Nk=
    groups: [http-servers]
  web3:
    ip: [10.8.0.146]
    ssh_public_key: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNGsgpvtJ9VeYhcl094C0h0fw26lQSa/6bAan1o8FB+cu35+lugsSSUXXbGT5sr+UYaWILB226RgO+aQ4mn49m0=
    groups: [http-servers]
  web-sh-abp-org-1:
    ip: [10.8.0.147]
    groups: [http-servers]
  web-yt-abp-me-1:
    ip: [10.8.0.148]
    groups: [http-servers]
  web-fb-abp-me-1:
    ip: [10.8.0.149]
    groups: [http-servers]
  web-aa-org-1:
    ip: [10.8.0.150]
    groups: [http-servers]


