---
adblockplus::hosts:
  absent-example:
    ensure: "absent"
  jessie0:
    ips: [10.8.0.101]
    os: "debian-jessie"
    public_key: &vagrant_box_jessie
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDkXTOj2JwvwlDaHbaMrDuosuRuU5ZuKe1EHNJa67ZxkB1a6Y1ObDxfYiYnvI5i9sQyUmmc5TrGAGGJs1BrriMaPayBaTSf3ymU2Rqxj3GZXuiioCxGV8I2R/aOhwvpbnVqZH5O99IuAZbrag5J/WhDWgWuk3gFrZxEwQmZW144tJH//I3b0oMAr3/arBViVeU52dHhKX9xdStTzFpWKUav/NoKKrgB91QKwPx8U6ymuDoCQU7qyTBnAX1sYuSwEMJzVRqtmKLybR4Xp5A94EMbJsgVbq4LrUrMo00FdLV0EGMmA2Kmd/9D+CuZXoD6/mWkzmaVfiUMKhrorM05voFp vagrant@contrib-jessie"
  precise0:
    ips: [10.8.0.102]
    os: "ubuntu-precise"
    public_key: &vagrant_box_precise
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDkXTOj2JwvwlDaHbaMrDuosuRuU5ZuKe1EHNJa67ZxkB1a6Y1ObDxfYiYnvI5i9sQyUmmc5TrGAGGJs1BrriMaPayBaTSf3ymU2Rqxj3GZXuiioCxGV8I2R/aOhwvpbnVqZH5O99IuAZbrag5J/WhDWgWuk3gFrZxEwQmZW144tJH//I3b0oMAr3/arBViVeU52dHhKX9xdStTzFpWKUav/NoKKrgB91QKwPx8U6ymuDoCQU7qyTBnAX1sYuSwEMJzVRqtmKLybR4Xp5A94EMbJsgVbq4LrUrMo00FdLV0EGMmA2Kmd/9D+CuZXoD6/mWkzmaVfiUMKhrorM05voFp vagrant@precise64"
  puppetmaster0:
    ips: [10.8.0.100]
    os: "debian-jessie"
    public_key: *vagrant_box_jessie
    role: "puppetmaster"
  filter1:
    ips: [10.8.0.120]
    os: "debian-jessie"
    public_key: *vagrant_box_jessie
    role: filterserver
    groups: [filter-servers]
  server4:
    ips: [10.8.0.99]
    role: monitoringserver
    os: "debian-jessie"
    public_key: *vagrant_box_jessie
    groups: [http-servers]
  codereview1:
    ips: [10.8.0.132]
    role: codereviewserver
    public_key: *vagrant_box_precise
    groups: [http-servers]
  download1:
    ips: [10.8.0.126]
    role: downloadserver
    os: "debian-jessie"
    public_key: *vagrant_box_jessie
    groups: [http-servers]
  filtermaster1:
    ips: [10.8.0.127]
    role: filtermasterserver
    os: "debian-jessie"
    public_key: *vagrant_box_jessie
  server10:
    ips: [10.8.0.105]
    role: intraforumserver
    public_key: *vagrant_box_precise
    groups: [http-servers]
  issues-2:
    ips: [10.8.0.131]
    role: issueserver
    os: "debian-jessie"
    public_key: *vagrant_box_jessie
    groups: [http-servers]
  update1:
    ips: [10.8.0.128]
    role: updateserver
    os: "debian-jessie"
    public_key: *vagrant_box_jessie
    groups: [http-servers]
  eyeo-com-1:
    ips: [10.8.0.129]
    role: web/eyeo
    os: "debian-jessie"
    public_key: *vagrant_box_jessie
    groups: [http-servers]
  adblockplus-org-1:
    ips: [10.8.0.145]
    role: web/adblockplus
    os: "debian-jessie"
    public_key: *vagrant_box_jessie
    groups: [http-servers]
  testpages-1:
    ips: [10.8.0.146]
    role: web/testpages
    os: "debian-jessie"
    public_key: *vagrant_box_jessie
    groups: [http-servers]
  share-1:
    ips: [10.8.0.147]
    role: web/share
    os: "debian-jessie"
    public_key: *vagrant_box_jessie
    groups: [http-servers]
  youtube-me-1:
    ips: [10.8.0.148]
    role: web/youtube
    os: "debian-jessie"
    public_key: *vagrant_box_jessie
    groups: [http-servers]
  facebook-me-1:
    ips: [10.8.0.149]
    role: web/facebook
    os: "debian-jessie"
    public_key: *vagrant_box_jessie
    groups: [http-servers]
  acceptableads-com-1:
    ips: [10.8.0.150]
    role: web/acceptableads
    os: "debian-jessie"
    public_key: *vagrant_box_jessie
    groups: [http-servers]
  hg1:
    ips: [10.8.0.152]
    role: hgwebserver
    os: "debian-jessie"
    public_key: *vagrant_box_jessie
    groups: [http-servers]
  build1:
    ips: [10.8.0.153]
    role: buildmasterserver
    os: "debian-jessie"
    public_key: *vagrant_box_jessie
    groups: [http-servers]
  adblockbrowser-org-1:
    ips: [10.8.0.154]
    role: web/adblockbrowser
    os: "debian-jessie"
    public_key: *vagrant_box_jessie
    groups: [http-servers]
  subscribe-1:
    ips: [10.8.0.155]
    role: web/subscribe
    os: "debian-jessie"
    public_key: *vagrant_box_jessie
    groups: [http-servers]
  easylist-1:
    ips: [10.8.0.156]
    role: web/easylist
    os: "debian-jessie"
    public_key: *vagrant_box_jessie
    groups: [http-servers]
  log1:
    ips: [10.8.0.210]
    role: logserver
    os: "debian-jessie"
    public_key: *vagrant_box_jessie
  logprocessor1:
    ips: [10.8.0.211]
    role: logprocessor
    os: "debian-jessie"
    public_key: *vagrant_box_jessie
  telemetry1:
    ips: [10.8.0.220]
    role: telemetryserver
    os: "debian-jessie"
    public_key: *vagrant_box_jessie
    groups: [http-servers]
  redirect-1:
    ips: [10.8.0.225]
    role: web/redirect/eyeo
    os: "debian-jessie"
    public_key: *vagrant_box_jessie
    groups: [http-servers]
  eyeofiles-1:
    ips: [10.8.0.226]
    role: web/fileserver/eyeofiles
    os: "debian-jessie"
    public_key: *vagrant_box_jessie
    groups: [http-servers]
  abp-builds-1:
    ips: [10.8.0.227]
    role: buildserver
    os: "debian-jessie"
    public_key: *vagrant_box_jessie

