---
servers:
  filter1:
    ip: [10.8.0.120]
    role: filterserver
    ssh_public_key: &vagrant_box
      AAAAB3NzaC1yc2EAAAADAQABAAABAQChpIwFFj2G8HeGbpe6tNLESGOKH2XiJ1A3w0iQydJoQjQMq/bd3lPexYDEFDI5orxe4KTtWXzqL74uco54x6DY35c7DbTBFlZi++DNfajh7zZVj+15ZXc5jefP8PO66gMgHUQ6dp0z8W5/p9OXdIwaWa8n083CzJn8IixF7/Q0bqBon7+7DNX/m+B7h+EfWizbzTrknrvGXXUYc1X7KY04fAIPa5S0TqEUliF2Yk1YHYyN5w7NUeLq3rd0YK8jFUy5DiKUgQ+ZYIKU3swcguZvFo38JBBrJns+1CKD28XQG6TguhWpzeVNMwcl+tm5LJjpGrTonprGgEPFC8Aa/+2T
    groups: [filter-servers]
  server4:
    ip: [10.8.0.99]
    role: monitoringserver
    ssh_public_key: *vagrant_box
    dns: server4.adblockplus.org
    groups: [http-servers]
  codereview1:
    ip: [10.8.0.132]
    role: codereviewserver
    ssh_public_key: *vagrant_box
    groups: [http-servers]
  download1:
    ip: [10.8.0.126]
    ssh_public_key: *vagrant_box
    dns: downloads.adblockplus.org
    groups: [http-servers]
  filtermaster1:
    ip: [10.8.0.127]
    role: filtermasterserver
    ssh_public_key: *vagrant_box
  server10:
    ip: [10.8.0.105]
    role: intraforumserver
    ssh_public_key: *vagrant_box
    dns: server10.adblockplus.org
    groups: [http-servers]
  issues1:
    ip: [10.8.0.131]
    ssh_public_key: *vagrant_box
    groups: [http-servers]
  stats1:
    ip: [10.8.0.130]
    ssh_public_key: *vagrant_box
    groups: [http-servers]
  update1:
    ip: [10.8.0.128]
    ssh_public_key: *vagrant_box
    groups: [http-servers]
  web1:
    ip: [10.8.0.129]
    role: web/eyeo
    ssh_public_key: *vagrant_box
    groups: [http-servers]
  web2:
    ip: [10.8.0.145]
    ssh_public_key: *vagrant_box
    groups: [http-servers]
  web3:
    ip: [10.8.0.146]
    role: web/testpages
    ssh_public_key: *vagrant_box
    groups: [http-servers]
  web-sh-abp-org-1:
    ip: [10.8.0.147]
    role: web/share
    ssh_public_key: *vagrant_box
    groups: [http-servers]
  web-yt-abp-me-1:
    ip: [10.8.0.148]
    role: web/youtube
    ssh_public_key: *vagrant_box
    groups: [http-servers]
  web-fb-abp-me-1:
    ip: [10.8.0.149]
    role: web/facebook
    ssh_public_key: *vagrant_box
    groups: [http-servers]
  web-aa-org-1:
    ip: [10.8.0.150]
    role: web/acceptableads
    ssh_public_key: *vagrant_box
    groups: [http-servers]
  hg1:
    ip: [10.8.0.152]
    role: hgwebserver
    ssh_public_key: *vagrant_box
    groups: [http-servers]
  web-abb-org-1:
    ip: [10.8.0.154]
    role: web/adblockbrowser
    ssh_public_key: *vagrant_box
    groups: [http-servers]
  log1:
    ip: [10.8.1.210]
    role: logserver
    ssh_public_key: *vagrant_box

