classes:
  filtermaster:
  filtermaster::iflu:

filtermaster::repos:
  - easylist
  - easylistgermany
  - easylistitaly
  - easylistchina
  - easylistcombinations
  - easylistspanish
  - malwaredomains
  - ruadlist
  - listefr
  - easylistdutch
  - antiadblockfilters
  - listear
  - customfilterlists
  - abpvn

filtermaster::repo_downloads:
  exceptionrules:
    target: exceptions
  contentblockerlists:
    static_files:
      - easylist+exceptionrules_content_blocker.json
      - easylist_content_blocker.json
      - easylist_min+exceptionrules_content_blocker.json
      - easylist_min_content_blocker.json
      - easylist+easylistchina-minified.json
      - easylist+easylistchina-minified+exceptionrules-minimal.json
      - easylist+easylistgermany-minified.json
      - easylist+easylistgermany-minified+exceptionrules-minimal.json
      - easylist+easylistitaly-minified.json
      - easylist+easylistitaly-minified+exceptionrules-minimal.json
      - easylist+easylistspanish-minified.json
      - easylist+easylistspanish-minified+exceptionrules-minimal.json
      - easylist+easylistdutch-minified.json
      - easylist+easylistdutch-minified+exceptionrules-minimal.json
      - easylist+liste_fr-minified.json
      - easylist+liste_fr-minified+exceptionrules-minimal.json
      - easylist+ruadlist-minified.json
      - easylist+ruadlist-minified+exceptionrules-minimal.json
      - easylist+abpvn-minified.json
      - easylist+abpvn-minified+exceptionrules-minimal.json
  crumbsfilterlist:
    static_files:
      - crumbs-privacy-friendly.txt

filtermaster::malwaredomains_mirrors:
  - http://mirror1.malwaredomains.com
  - http://mirror2.malwaredomains.com

filtermaster::iflu::filterlists:
  easylist: {}

