classes:
  adblockplus::mercurial::extension::hggit:
  hgweb:
    domain: "hg.adblockplus.org"
    is_default: true
    custom_config: |
      location /gitlab_webhook {
        proxy_pass http://127.0.0.1:8000;
      }
  hgweb::endpoint:

fail2ban::jails:
  CRAWLERS:
    filter: apache-badbots
    logpath: '/var/log/nginx/access_log_hg'
    banaction: 'iptables-multiport'
    port: 'http,https'

