#!/bin/bash

app_dir="/opt/discourse"

cd $app_dir

export GEM_HOME=~discourse/.gems
bundle install

$GEM_HOME/bin/rake assets:precompile RAILS_ENV="production"

[[ -f /etc/init.d/spawn-fcgi ]] && sudo /etc/init.d/spawn-fcgi stop

$GEM_HOME/bin/rake db:migrate RAILS_ENV="production"

[[ -f /etc/init.d/spawn-fcgi ]] && sudo /etc/init.d/spawn-fcgi start
