#!/bin/bash

ANWIKI_ROOT=/var/www/adblockplus.org/anwiki
PHP_ROOT=/var/www/adblockplus.org/phproot

TEMP_DIR="/tmp/anwiki-$$"
rm -rf "$TEMP_DIR"
mkdir "$TEMP_DIR"
cd "$TEMP_DIR"

LOCAL_ANWIKI_REPOSITORY="/mnt/local_anwiki_repository"

if [[ -d $LOCAL_ANWIKI_REPOSITORY ]]; then
    cp -r "$LOCAL_ANWIKI_REPOSITORY" anwiki
    rm -r anwiki/.hg*
else
    hg clone https://hg.adblockplus.org/anwiki anwiki-hg &>/dev/null

    if [[ $? != 0 ]]; then
	echo "Unable to clone anwiki repository" >&2
	exit 1
    fi

    hg archive -R anwiki-hg -r local anwiki
fi

find anwiki/anwiki -name .htaccess -exec rm '{}' \;
find anwiki/anwiki -name index.html -exec rm '{}' \;
find anwiki/anwiki/_override -name '*.cfg.php' -exec rm '{}' \;
rm anwiki/anwiki/htaccess-DISABLED
rm anwiki/anwiki/_anwiki-override-DISABLED.inc.php

mkdir -p "$ANWIKI_ROOT"
mkdir -p "$PHP_ROOT"

SITE_DIR="anwiki/anwiki"
chown -R www-data:www-data anwiki/anwiki
cp -prf "$SITE_DIR"/{_addons,_addons-static,_override,_override-static,default,default-static,sources,anwiki.inc.php} "$ANWIKI_ROOT"
cp -prf "$SITE_DIR"/{index.php,engine.inc.php} "$PHP_ROOT"

WRITABLE_DIR="$ANWIKI_ROOT/_writable"

mkdir -p "$WRITABLE_DIR/"{status,tmp}

CACHE_DIR="$WRITABLE_DIR/cache"
rm -rf "$CACHE_DIR"
mkdir -p "$CACHE_DIR/"{config,content/bygroup,content/byid,content/byname,system}

chown -R www-data:www-data "$WRITABLE_DIR"

ACLSDRIVER_CONFIGRULES="$ANWIKI_ROOT/_override/drivers/aclsdrivers/aclsdriver_configrules/aclsdriver_configrules.cfg.php"
touch "$ACLSDRIVER_CONFIGRULES"
chown www-data "$ACLSDRIVER_CONFIGRULES"

rm -rf "$TEMP_DIR"
