#!/bin/bash

ANWIKI_ROOT=/var/www/adblockplus.org/anwiki
PHP_ROOT=/var/www/adblockplus.org/phproot

TEMP_DIR="/tmp/anwiki-$$"
rm -rf "$TEMP_DIR"
mkdir "$TEMP_DIR"
cd "$TEMP_DIR"

hg clone https://hg.adblockplus.org/anwiki anwiki-hg &>/dev/null
hg archive -R anwiki-hg -r local anwiki
rm -rf anwiki-hg

find anwiki/anwiki -name .htaccess -exec rm '{}' \;
find anwiki/anwiki -name index.html -exec rm '{}' \;
find anwiki/anwiki/_override -name '*.cfg.php' -exec rm '{}' \;
rm anwiki/anwiki/htaccess-DISABLED
rm anwiki/anwiki/_anwiki-override-DISABLED.inc.php

SITE_DIR="anwiki/anwiki"
chown -R www-data:www-data anwiki/anwiki
cp -prf "$SITE_DIR"/{_addons,_addons-static,_override,_override-static,default,default-static,sources,anwiki.inc.php} "$ANWIKI_ROOT"
cp -prf "$SITE_DIR"/{index.php,engine.inc.php} "$PHP_ROOT"

CACHE_DIR="$ANWIKI_ROOT/_writable/cache"
rm -rf "$CACHE_DIR"
mkdir -p "$CACHE_DIR/{config,content/bygroup,content/byid,content/byname,system}"
chown -R www-data:www-data "$CACHE_DIR"

rm -rf "$TEMP_DIR"
