#!/bin/bash
#
# Init file for PHP FastCGI server daemon
#
# /etc/init.d/php-fastcgi
#
### BEGIN INIT INFO
# Provides:          php-fastcgi
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       PHP FastCGI server
### END INIT INFO

# Define some functions only available on openSUSE systems.
# Not a great permanent solution, but makes porting easier.

if [[ -f /etc/rc.status ]]; then
  . /etc/rc.status
else
  rc_status()
  {
    _rc_status=$?
    (( _rc_status == 0 )) && echo "done" || echo "failed"
  }

  rc_reset()
  {
    _rc_status=0
  }

  rc_exit()
  {
    exit $_rc_status
  }
fi

if ! type killproc &>/dev/null ; then
  killproc()
  {
    local pid=`cat "$PID_FILE"`
    [[ -n $pid ]] && kill "$pid" || true
  }
fi

# pull in sysconfig settings
[ -f /etc/default/php-fastcgi ] && . /etc/default/php-fastcgi

prog="php5-cgi"

# Some functions to make the below more readable
SPAWN=/usr/bin/spawn-fcgi
PHP=/usr/bin/php5-cgi
FCGI_SOCKET=/tmp/php-fastcgi.sock
PID_FILE=/var/run/php-fastcgi.pid

start()
{
  echo -n $"Starting $prog: "

  if [[ -f $PID_FILE ]]; then
    echo "already running"
  else
    $SPAWN $OPTIONS -f $PHP -s $FCGI_SOCKET -C $PHP_FCGI_CHILDREN -P $PID_FILE -u $EXEC_AS_USER &>/dev/null
    rc_status -v
    chmod go+w $FCGI_SOCKET
  fi
}

stop()
{
  echo -n $"Stopping $prog: "

  if [[ ! -f $PID_FILE ]]; then
    echo "not running"
  else
    killproc -p $PID_FILE php5
    rc_status -v
    sleep 1
    rm -f $PID_FILE
    rm -f $FCGI_SOCKET
  fi
}

rc_reset
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac
rc_exit
